# k8s/app.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: local-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-app
  namespace: local-app
  labels:
    app: local-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-app
  template:
    metadata:
      labels:
        app: local-app
    spec:
      containers:
      - name: app
        image: netinhos89/local-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "1.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: local-app-service
  namespace: local-app
spec:
  selector:
    app: local-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP